version: '3.8'

services:
  dineflow-db:
    image: postgres:16-alpine
    container_name: dineflow_postgres
    environment:
      - POSTGRES_DB=dineflow_db
      - POSTGRES_USER=dineflow_user
      - POSTGRES_PASSWORD=dineflow_secret
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always